/**
 * Potato API
 * Service for generating title pages
 *
 * OpenAPI spec version: 1.1
 * Contact: nelunull@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LoginOutDto {
  id?: number;
  fullName?: string;
  login?: string;
  password?: string;
  email?: string;
  token?: string;
}
