/**
 * Potato API
 * Service for generating title pages
 *
 * OpenAPI spec version: 1.1
 * Contact: nelunull@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TemplateInfoDto {
  id?: number;
  userId?: number;
  faculty?: string;
  department?: string;
  jobName?: string;
  subject?: string;
  lessonName?: string;
  fullNameTeacher?: string;
  courseNumber?: string;
  groupName?: string;
}
